<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20241230140810 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE directors DROP CONSTRAINT fk_a6adadc4acf64f5f');
        $this->addSql('ALTER TABLE directors DROP CONSTRAINT fk_a6adadc4a76ed395');
        $this->addSql('DROP TABLE directors');
        $this->addSql('ALTER TABLE director DROP CONSTRAINT fk_1e90d3f067b3b43d');
        $this->addSql('DROP INDEX idx_1e90d3f067b3b43d');
        $this->addSql('ALTER TABLE director RENAME COLUMN users_id TO user_id');
        $this->addSql('ALTER TABLE director ADD CONSTRAINT FK_1E90D3F0A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_1E90D3F0A76ED395 ON director (user_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('CREATE TABLE directors (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, institut_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_a6adadc4a76ed395 ON directors (user_id)');
        $this->addSql('CREATE INDEX idx_a6adadc4acf64f5f ON directors (institut_id)');
        $this->addSql('ALTER TABLE directors ADD CONSTRAINT fk_a6adadc4acf64f5f FOREIGN KEY (institut_id) REFERENCES institutions (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE directors ADD CONSTRAINT fk_a6adadc4a76ed395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE director DROP CONSTRAINT FK_1E90D3F0A76ED395');
        $this->addSql('DROP INDEX IDX_1E90D3F0A76ED395');
        $this->addSql('ALTER TABLE director RENAME COLUMN user_id TO users_id');
        $this->addSql('ALTER TABLE director ADD CONSTRAINT fk_1e90d3f067b3b43d FOREIGN KEY (users_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_1e90d3f067b3b43d ON director (users_id)');
    }
}
