<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260406160921 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE user_innovative_education DROP CONSTRAINT fk_4043467aa76ed395');
        $this->addSql('ALTER TABLE user_innovative_education DROP CONSTRAINT fk_4043467ae4776e89');
        $this->addSql('ALTER TABLE user_social_activities DROP CONSTRAINT fk_83bda60ca76ed395');
        $this->addSql('ALTER TABLE user_social_activities DROP CONSTRAINT fk_83bda60c8922b495');
        $this->addSql('ALTER TABLE user_personal_awards DROP CONSTRAINT fk_c3ba6366a76ed395');
        $this->addSql('ALTER TABLE user_personal_awards DROP CONSTRAINT fk_c3ba636610f3a34');
        $this->addSql('ALTER TABLE social_activities_subtitle DROP CONSTRAINT fk_cfba2604a9f87bd');
        $this->addSql('ALTER TABLE research_activities_subtitle DROP CONSTRAINT fk_9c84e5e712469de2');
        $this->addSql('ALTER TABLE user_research_activities_list DROP CONSTRAINT fk_efbe6d92a76ed395');
        $this->addSql('ALTER TABLE user_research_activities_list DROP CONSTRAINT fk_efbe6d9210f3a34');
        $this->addSql('ALTER TABLE user_info DROP CONSTRAINT fk_b1087d9ea76ed395');
        $this->addSql('ALTER TABLE user_info DROP CONSTRAINT fk_b1087d9ee3badb69');
        $this->addSql('ALTER TABLE user_info DROP CONSTRAINT fk_b1087d9edd842e46');
        $this->addSql('ALTER TABLE personal_awards_subtitle DROP CONSTRAINT fk_1f44198a9f87bd');
        $this->addSql('DROP TABLE offence_list');
        $this->addSql('DROP TABLE user_innovative_education');
        $this->addSql('DROP TABLE user_social_activities');
        $this->addSql('DROP TABLE user_personal_awards');
        $this->addSql('DROP TABLE social_activities_subtitle');
        $this->addSql('DROP TABLE social_activities_list');
        $this->addSql('DROP TABLE institutions');
        $this->addSql('DROP TABLE research_activities_list');
        $this->addSql('DROP TABLE research_activities_subtitle');
        $this->addSql('DROP TABLE user_research_activities_list');
        $this->addSql('DROP TABLE user_info');
        $this->addSql('DROP TABLE personal_awards');
        $this->addSql('DROP TABLE personal_awards_subtitle');
        $this->addSql('ALTER TABLE institute_answer ADD academic_year_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE institute_answer ADD CONSTRAINT FK_2B2962FCC54F3401 FOREIGN KEY (academic_year_id) REFERENCES years (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_2B2962FCC54F3401 ON institute_answer (academic_year_id)');
        $this->addSql('ALTER TABLE results_of_year DROP CONSTRAINT fk_a932742d9b6b5fba');
        $this->addSql('DROP INDEX idx_a932742d9b6b5fba');
        $this->addSql('ALTER TABLE results_of_year RENAME COLUMN account_id TO teacher_id');
        $this->addSql('ALTER TABLE results_of_year ADD CONSTRAINT FK_A932742D41807E1D FOREIGN KEY (teacher_id) REFERENCES teacher (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_A932742D41807E1D ON results_of_year (teacher_id)');
        $this->addSql('ALTER TABLE stage ADD is_permanent BOOLEAN DEFAULT false');
        $this->addSql('ALTER TABLE teacher_answer ADD academic_year_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE teacher_answer ADD CONSTRAINT FK_CF5698D0C54F3401 FOREIGN KEY (academic_year_id) REFERENCES years (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_CF5698D0C54F3401 ON teacher_answer (academic_year_id)');
        $this->addSql('ALTER TABLE user_offence DROP CONSTRAINT fk_4df9df7aa9dfb1a4');
        $this->addSql('DROP INDEX idx_4df9df7aa9dfb1a4');
        $this->addSql('ALTER TABLE user_offence DROP offence_list_id');
        $this->addSql('ALTER TABLE years ADD is_current BOOLEAN DEFAULT false');
        $this->addSql('ALTER TABLE years ADD is_locked BOOLEAN DEFAULT false');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('CREATE TABLE offence_list (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, points INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE user_innovative_education (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, link TEXT NOT NULL, user_id INT DEFAULT NULL, innovative_education_subtitle_id INT DEFAULT NULL, status VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_4043467ae4776e89 ON user_innovative_education (innovative_education_subtitle_id)');
        $this->addSql('CREATE INDEX idx_4043467aa76ed395 ON user_innovative_education (user_id)');
        $this->addSql('CREATE TABLE user_social_activities (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, link TEXT NOT NULL, user_id INT DEFAULT NULL, social_activities_subtitle_id INT DEFAULT NULL, status VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_83bda60c8922b495 ON user_social_activities (social_activities_subtitle_id)');
        $this->addSql('CREATE INDEX idx_83bda60ca76ed395 ON user_social_activities (user_id)');
        $this->addSql('CREATE TABLE user_personal_awards (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, link TEXT NOT NULL, user_id INT DEFAULT NULL, subtitle_id INT DEFAULT NULL, status VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_c3ba636610f3a34 ON user_personal_awards (subtitle_id)');
        $this->addSql('CREATE INDEX idx_c3ba6366a76ed395 ON user_personal_awards (user_id)');
        $this->addSql('CREATE TABLE social_activities_subtitle (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) DEFAULT NULL, points INT NOT NULL, title_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_cfba2604a9f87bd ON social_activities_subtitle (title_id)');
        $this->addSql('CREATE TABLE social_activities_list (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE institutions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, university VARCHAR(255) NOT NULL, reduction VARCHAR(255) NOT NULL, total_teachers INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE research_activities_list (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE research_activities_subtitle (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) DEFAULT NULL, points INT NOT NULL, category_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_9c84e5e712469de2 ON research_activities_subtitle (category_id)');
        $this->addSql('CREATE TABLE user_research_activities_list (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT DEFAULT NULL, link TEXT NOT NULL, subtitle_id INT DEFAULT NULL, status VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_efbe6d9210f3a34 ON user_research_activities_list (subtitle_id)');
        $this->addSql('CREATE INDEX idx_efbe6d92a76ed395 ON user_research_activities_list (user_id)');
        $this->addSql('CREATE TABLE user_info (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, user_id INT DEFAULT NULL, regular VARCHAR(255) NOT NULL, email VARCHAR(255) DEFAULT NULL, institutions_id INT DEFAULT NULL, position_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_b1087d9ea76ed395 ON user_info (user_id)');
        $this->addSql('CREATE INDEX idx_b1087d9edd842e46 ON user_info (position_id)');
        $this->addSql('CREATE INDEX idx_b1087d9ee3badb69 ON user_info (institutions_id)');
        $this->addSql('CREATE TABLE personal_awards (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE personal_awards_subtitle (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, points INT NOT NULL, title_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_1f44198a9f87bd ON personal_awards_subtitle (title_id)');
        $this->addSql('ALTER TABLE user_innovative_education ADD CONSTRAINT fk_4043467aa76ed395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_innovative_education ADD CONSTRAINT fk_4043467ae4776e89 FOREIGN KEY (innovative_education_subtitle_id) REFERENCES innovative_education_subtitle (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_social_activities ADD CONSTRAINT fk_83bda60ca76ed395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_social_activities ADD CONSTRAINT fk_83bda60c8922b495 FOREIGN KEY (social_activities_subtitle_id) REFERENCES social_activities_subtitle (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_personal_awards ADD CONSTRAINT fk_c3ba6366a76ed395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_personal_awards ADD CONSTRAINT fk_c3ba636610f3a34 FOREIGN KEY (subtitle_id) REFERENCES personal_awards_subtitle (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE social_activities_subtitle ADD CONSTRAINT fk_cfba2604a9f87bd FOREIGN KEY (title_id) REFERENCES social_activities_list (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE research_activities_subtitle ADD CONSTRAINT fk_9c84e5e712469de2 FOREIGN KEY (category_id) REFERENCES research_activities_list (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_research_activities_list ADD CONSTRAINT fk_efbe6d92a76ed395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_research_activities_list ADD CONSTRAINT fk_efbe6d9210f3a34 FOREIGN KEY (subtitle_id) REFERENCES research_activities_subtitle (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_info ADD CONSTRAINT fk_b1087d9ea76ed395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_info ADD CONSTRAINT fk_b1087d9ee3badb69 FOREIGN KEY (institutions_id) REFERENCES institutions (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_info ADD CONSTRAINT fk_b1087d9edd842e46 FOREIGN KEY (position_id) REFERENCES "position" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE personal_awards_subtitle ADD CONSTRAINT fk_1f44198a9f87bd FOREIGN KEY (title_id) REFERENCES personal_awards (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE years DROP is_current');
        $this->addSql('ALTER TABLE years DROP is_locked');
        $this->addSql('ALTER TABLE teacher_answer DROP CONSTRAINT FK_CF5698D0C54F3401');
        $this->addSql('DROP INDEX IDX_CF5698D0C54F3401');
        $this->addSql('ALTER TABLE teacher_answer DROP academic_year_id');
        $this->addSql('ALTER TABLE stage DROP is_permanent');
        $this->addSql('ALTER TABLE user_offence ADD offence_list_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE user_offence ADD CONSTRAINT fk_4df9df7aa9dfb1a4 FOREIGN KEY (offence_list_id) REFERENCES offence_list (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_4df9df7aa9dfb1a4 ON user_offence (offence_list_id)');
        $this->addSql('ALTER TABLE results_of_year DROP CONSTRAINT FK_A932742D41807E1D');
        $this->addSql('DROP INDEX IDX_A932742D41807E1D');
        $this->addSql('ALTER TABLE results_of_year RENAME COLUMN teacher_id TO account_id');
        $this->addSql('ALTER TABLE results_of_year ADD CONSTRAINT fk_a932742d9b6b5fba FOREIGN KEY (account_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_a932742d9b6b5fba ON results_of_year (account_id)');
        $this->addSql('ALTER TABLE institute_answer DROP CONSTRAINT FK_2B2962FCC54F3401');
        $this->addSql('DROP INDEX IDX_2B2962FCC54F3401');
        $this->addSql('ALTER TABLE institute_answer DROP academic_year_id');
    }
}
