<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260115055351 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE institution_answer DROP CONSTRAINT fk_4f83183c10405986');
        $this->addSql('ALTER TABLE institution_answer DROP CONSTRAINT fk_4f83183c1e27f6bf');
        $this->addSql('ALTER TABLE institution_question_option DROP CONSTRAINT fk_74fa3a331e27f6bf');
        $this->addSql('DROP TABLE institution_answer');
        $this->addSql('DROP TABLE institution_question_option');
        $this->addSql('DROP TABLE institution_question');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('CREATE TABLE institution_answer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, link TEXT DEFAULT NULL, status BOOLEAN NOT NULL, institution_id INT NOT NULL, question_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_4f83183c1e27f6bf ON institution_answer (question_id)');
        $this->addSql('CREATE INDEX idx_4f83183c10405986 ON institution_answer (institution_id)');
        $this->addSql('CREATE TABLE institution_question_option (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) DEFAULT NULL, option BOOLEAN NOT NULL, link BOOLEAN NOT NULL, question_id INT DEFAULT NULL, points INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_74fa3a331e27f6bf ON institution_question_option (question_id)');
        $this->addSql('CREATE TABLE institution_question (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE institution_answer ADD CONSTRAINT fk_4f83183c10405986 FOREIGN KEY (institution_id) REFERENCES institutions (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE institution_answer ADD CONSTRAINT fk_4f83183c1e27f6bf FOREIGN KEY (question_id) REFERENCES institution_question_option (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE institution_question_option ADD CONSTRAINT fk_74fa3a331e27f6bf FOREIGN KEY (question_id) REFERENCES institution_question (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
}
