<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260404055347 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE expert_adjustment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, points INT NOT NULL, reason TEXT NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expert_id INT NOT NULL, target_teacher_id INT DEFAULT NULL, target_institute_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_90221747C5568CE4 ON expert_adjustment (expert_id)');
        $this->addSql('CREATE INDEX IDX_90221747736CA68C ON expert_adjustment (target_teacher_id)');
        $this->addSql('CREATE INDEX IDX_902217478929DC1D ON expert_adjustment (target_institute_id)');
        $this->addSql('ALTER TABLE expert_adjustment ADD CONSTRAINT FK_90221747C5568CE4 FOREIGN KEY (expert_id) REFERENCES expert (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE expert_adjustment ADD CONSTRAINT FK_90221747736CA68C FOREIGN KEY (target_teacher_id) REFERENCES teacher (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE expert_adjustment ADD CONSTRAINT FK_902217478929DC1D FOREIGN KEY (target_institute_id) REFERENCES institute (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_expert_point DROP CONSTRAINT fk_95b98f7ec5568ce4');
        $this->addSql('ALTER TABLE user_expert_point DROP CONSTRAINT fk_95b98f7e41807e1d');
        $this->addSql('DROP TABLE user_expert_point');
        $this->addSql('ALTER TABLE expert DROP CONSTRAINT fk_4f1b93429b6b5fba');
        $this->addSql('DROP INDEX uniq_4f1b93429b6b5fba');
        $this->addSql('ALTER TABLE expert RENAME COLUMN account_id TO teacher_id');
        $this->addSql('ALTER TABLE expert ADD CONSTRAINT FK_4F1B934241807E1D FOREIGN KEY (teacher_id) REFERENCES teacher (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4F1B934241807E1D ON expert (teacher_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('CREATE TABLE user_expert_point (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, point INT NOT NULL, expert_id INT DEFAULT NULL, teacher_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_95b98f7e41807e1d ON user_expert_point (teacher_id)');
        $this->addSql('CREATE INDEX idx_95b98f7ec5568ce4 ON user_expert_point (expert_id)');
        $this->addSql('ALTER TABLE user_expert_point ADD CONSTRAINT fk_95b98f7ec5568ce4 FOREIGN KEY (expert_id) REFERENCES expert (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_expert_point ADD CONSTRAINT fk_95b98f7e41807e1d FOREIGN KEY (teacher_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE expert_adjustment DROP CONSTRAINT FK_90221747C5568CE4');
        $this->addSql('ALTER TABLE expert_adjustment DROP CONSTRAINT FK_90221747736CA68C');
        $this->addSql('ALTER TABLE expert_adjustment DROP CONSTRAINT FK_902217478929DC1D');
        $this->addSql('DROP TABLE expert_adjustment');
        $this->addSql('ALTER TABLE expert DROP CONSTRAINT FK_4F1B934241807E1D');
        $this->addSql('DROP INDEX UNIQ_4F1B934241807E1D');
        $this->addSql('ALTER TABLE expert RENAME COLUMN teacher_id TO account_id');
        $this->addSql('ALTER TABLE expert ADD CONSTRAINT fk_4f1b93429b6b5fba FOREIGN KEY (account_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE UNIQUE INDEX uniq_4f1b93429b6b5fba ON expert (account_id)');
    }
}
