<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250104170656 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE institution_question (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE institution_question_option (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) DEFAULT NULL, option BOOLEAN NOT NULL, link BOOLEAN NOT NULL, question_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_74FA3A331E27F6BF ON institution_question_option (question_id)');
        $this->addSql('ALTER TABLE institution_question_option ADD CONSTRAINT FK_74FA3A331E27F6BF FOREIGN KEY (question_id) REFERENCES institution_question (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE institution_question_option DROP CONSTRAINT FK_74FA3A331E27F6BF');
        $this->addSql('DROP TABLE institution_question');
        $this->addSql('DROP TABLE institution_question_option');
    }
}
