<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240319150209 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE social_activities_list (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE social_activities_subtitle (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) DEFAULT NULL, points INT NOT NULL, title_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_CFBA2604A9F87BD ON social_activities_subtitle (title_id)');
        $this->addSql('CREATE TABLE user_social_activities (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, link TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE social_activities_subtitle ADD CONSTRAINT FK_CFBA2604A9F87BD FOREIGN KEY (title_id) REFERENCES social_activities_list (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE social_activities_subtitle DROP CONSTRAINT FK_CFBA2604A9F87BD');
        $this->addSql('DROP TABLE social_activities_list');
        $this->addSql('DROP TABLE social_activities_subtitle');
        $this->addSql('DROP TABLE user_social_activities');
    }
}
