<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240325063458 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE user_offence (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT DEFAULT NULL, offence_list_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4DF9DF7AA76ED395 ON user_offence (user_id)');
        $this->addSql('CREATE INDEX IDX_4DF9DF7AA9DFB1A4 ON user_offence (offence_list_id)');
        $this->addSql('ALTER TABLE user_offence ADD CONSTRAINT FK_4DF9DF7AA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_offence ADD CONSTRAINT FK_4DF9DF7AA9DFB1A4 FOREIGN KEY (offence_list_id) REFERENCES offence_list (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_info DROP CONSTRAINT fk_b1087d9ea9dfb1a4');
        $this->addSql('DROP INDEX idx_b1087d9ea9dfb1a4');
        $this->addSql('ALTER TABLE user_info DROP offence_list_id');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE user_offence DROP CONSTRAINT FK_4DF9DF7AA76ED395');
        $this->addSql('ALTER TABLE user_offence DROP CONSTRAINT FK_4DF9DF7AA9DFB1A4');
        $this->addSql('DROP TABLE user_offence');
        $this->addSql('ALTER TABLE user_info ADD offence_list_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE user_info ADD CONSTRAINT fk_b1087d9ea9dfb1a4 FOREIGN KEY (offence_list_id) REFERENCES offence_list (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_b1087d9ea9dfb1a4 ON user_info (offence_list_id)');
    }
}
