<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20241121111529 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE results_of_year (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, points INT DEFAULT NULL, year_id INT NOT NULL, account_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A932742D40C1FEA7 ON results_of_year (year_id)');
        $this->addSql('CREATE INDEX IDX_A932742D9B6B5FBA ON results_of_year (account_id)');
        $this->addSql('CREATE TABLE years (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE results_of_year ADD CONSTRAINT FK_A932742D40C1FEA7 FOREIGN KEY (year_id) REFERENCES years (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE results_of_year ADD CONSTRAINT FK_A932742D9B6B5FBA FOREIGN KEY (account_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE results_of_year DROP CONSTRAINT FK_A932742D40C1FEA7');
        $this->addSql('ALTER TABLE results_of_year DROP CONSTRAINT FK_A932742D9B6B5FBA');
        $this->addSql('DROP TABLE results_of_year');
        $this->addSql('DROP TABLE years');
    }
}
