<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260115060703 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE question_subtitle (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) DEFAULT NULL, point INT NOT NULL, title_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_328D27BDA9F87BD ON question_subtitle (title_id)');
        $this->addSql('CREATE TABLE question_title (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) DEFAULT NULL, stage_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1BDD696F2298D193 ON question_title (stage_id)');
        $this->addSql('CREATE TABLE stage (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) DEFAULT NULL, active BOOLEAN DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE teacher_answer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, link TEXT DEFAULT NULL, active BOOLEAN NOT NULL, teacher_id INT DEFAULT NULL, subtitle_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_CF5698D041807E1D ON teacher_answer (teacher_id)');
        $this->addSql('CREATE INDEX IDX_CF5698D010F3A34 ON teacher_answer (subtitle_id)');
        $this->addSql('ALTER TABLE question_subtitle ADD CONSTRAINT FK_328D27BDA9F87BD FOREIGN KEY (title_id) REFERENCES question_title (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE question_title ADD CONSTRAINT FK_1BDD696F2298D193 FOREIGN KEY (stage_id) REFERENCES stage (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE teacher_answer ADD CONSTRAINT FK_CF5698D041807E1D FOREIGN KEY (teacher_id) REFERENCES teacher (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE teacher_answer ADD CONSTRAINT FK_CF5698D010F3A34 FOREIGN KEY (subtitle_id) REFERENCES question_subtitle (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE question_subtitle DROP CONSTRAINT FK_328D27BDA9F87BD');
        $this->addSql('ALTER TABLE question_title DROP CONSTRAINT FK_1BDD696F2298D193');
        $this->addSql('ALTER TABLE teacher_answer DROP CONSTRAINT FK_CF5698D041807E1D');
        $this->addSql('ALTER TABLE teacher_answer DROP CONSTRAINT FK_CF5698D010F3A34');
        $this->addSql('DROP TABLE question_subtitle');
        $this->addSql('DROP TABLE question_title');
        $this->addSql('DROP TABLE stage');
        $this->addSql('DROP TABLE teacher_answer');
    }
}
