<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251219123905 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE institute (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, reduction VARCHAR(255) DEFAULT NULL, teacher_total INT DEFAULT NULL, organization_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_CA55B5D032C8A3DE ON institute (organization_id)');
        $this->addSql('CREATE TABLE organization (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C1EE637C5E237E06 ON organization (name)');
        $this->addSql('CREATE TABLE teacher_organization (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, teacher_id INT NOT NULL, organization_id INT NOT NULL, institute_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5731974E41807E1D ON teacher_organization (teacher_id)');
        $this->addSql('CREATE INDEX IDX_5731974E32C8A3DE ON teacher_organization (organization_id)');
        $this->addSql('CREATE INDEX IDX_5731974E697B0F4C ON teacher_organization (institute_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_TEACHER_ORG ON teacher_organization (teacher_id, organization_id)');
        $this->addSql('ALTER TABLE institute ADD CONSTRAINT FK_CA55B5D032C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE teacher_organization ADD CONSTRAINT FK_5731974E41807E1D FOREIGN KEY (teacher_id) REFERENCES teacher (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE teacher_organization ADD CONSTRAINT FK_5731974E32C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE teacher_organization ADD CONSTRAINT FK_5731974E697B0F4C FOREIGN KEY (institute_id) REFERENCES institute (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE position ADD reduction VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE teacher ADD middle_name VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE teacher ADD has_trousers BOOLEAN DEFAULT NULL');
        $this->addSql('ALTER TABLE teacher ADD position_id INT NOT NULL');
        $this->addSql('ALTER TABLE teacher ADD CONSTRAINT FK_B0F6A6D5DD842E46 FOREIGN KEY (position_id) REFERENCES position (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_B0F6A6D5DD842E46 ON teacher (position_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE institute DROP CONSTRAINT FK_CA55B5D032C8A3DE');
        $this->addSql('ALTER TABLE teacher_organization DROP CONSTRAINT FK_5731974E41807E1D');
        $this->addSql('ALTER TABLE teacher_organization DROP CONSTRAINT FK_5731974E32C8A3DE');
        $this->addSql('ALTER TABLE teacher_organization DROP CONSTRAINT FK_5731974E697B0F4C');
        $this->addSql('DROP TABLE institute');
        $this->addSql('DROP TABLE organization');
        $this->addSql('DROP TABLE teacher_organization');
        $this->addSql('ALTER TABLE position DROP reduction');
        $this->addSql('ALTER TABLE teacher DROP CONSTRAINT FK_B0F6A6D5DD842E46');
        $this->addSql('DROP INDEX IDX_B0F6A6D5DD842E46');
        $this->addSql('ALTER TABLE teacher DROP middle_name');
        $this->addSql('ALTER TABLE teacher DROP has_trousers');
        $this->addSql('ALTER TABLE teacher DROP position_id');
    }
}
