<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250221134121 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE expert (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, job_title VARCHAR(255) NOT NULL, account_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4F1B93429B6B5FBA ON expert (account_id)');
        $this->addSql('CREATE TABLE user_expert_point (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, point INT NOT NULL, expert_id INT DEFAULT NULL, teacher_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_95B98F7EC5568CE4 ON user_expert_point (expert_id)');
        $this->addSql('CREATE INDEX IDX_95B98F7E41807E1D ON user_expert_point (teacher_id)');
        $this->addSql('ALTER TABLE expert ADD CONSTRAINT FK_4F1B93429B6B5FBA FOREIGN KEY (account_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_expert_point ADD CONSTRAINT FK_95B98F7EC5568CE4 FOREIGN KEY (expert_id) REFERENCES expert (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_expert_point ADD CONSTRAINT FK_95B98F7E41807E1D FOREIGN KEY (teacher_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE expert DROP CONSTRAINT FK_4F1B93429B6B5FBA');
        $this->addSql('ALTER TABLE user_expert_point DROP CONSTRAINT FK_95B98F7EC5568CE4');
        $this->addSql('ALTER TABLE user_expert_point DROP CONSTRAINT FK_95B98F7E41807E1D');
        $this->addSql('DROP TABLE expert');
        $this->addSql('DROP TABLE user_expert_point');
    }
}
