<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20241118082336 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE directors (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, institut_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A6ADADC43DC7610E ON directors (user_id)');
        $this->addSql('CREATE INDEX IDX_A6ADADC4ACF64F5F ON directors (institut_id)');
        $this->addSql('CREATE TABLE inst_qwith_link (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, points INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE user_inst_qwith_link (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, link TEXT NOT NULL, status VARCHAR(255) NOT NULL, director_id INT NOT NULL, award_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6EF7F8BC899FB366 ON user_inst_qwith_link (director_id)');
        $this->addSql('CREATE INDEX IDX_6EF7F8BC3D5282CF ON user_inst_qwith_link (award_id)');
        $this->addSql('ALTER TABLE directors ADD CONSTRAINT FK_A6ADADC43DC7610E FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE directors ADD CONSTRAINT FK_A6ADADC4ACF64F5F FOREIGN KEY (institut_id) REFERENCES institutions (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_inst_qwith_link ADD CONSTRAINT FK_6EF7F8BC899FB366 FOREIGN KEY (director_id) REFERENCES directors (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_inst_qwith_link ADD CONSTRAINT FK_6EF7F8BC3D5282CF FOREIGN KEY (award_id) REFERENCES inst_qwith_link (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE directors DROP CONSTRAINT FK_A6ADADC43DC7610E');
        $this->addSql('ALTER TABLE directors DROP CONSTRAINT FK_A6ADADC4ACF64F5F');
        $this->addSql('ALTER TABLE user_inst_qwith_link DROP CONSTRAINT FK_6EF7F8BC899FB366');
        $this->addSql('ALTER TABLE user_inst_qwith_link DROP CONSTRAINT FK_6EF7F8BC3D5282CF');
        $this->addSql('DROP TABLE directors');
        $this->addSql('DROP TABLE inst_qwith_link');
        $this->addSql('DROP TABLE user_inst_qwith_link');
    }
}
