<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260304072904 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE institute_answer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, link TEXT DEFAULT NULL, active BOOLEAN NOT NULL, institute_id INT DEFAULT NULL, subtitle_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2B2962FC697B0F4C ON institute_answer (institute_id)');
        $this->addSql('CREATE INDEX IDX_2B2962FC10F3A34 ON institute_answer (subtitle_id)');
        $this->addSql('CREATE TABLE institute_question_subtitle (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, point INT NOT NULL, title_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E2CE34E5A9F87BD ON institute_question_subtitle (title_id)');
        $this->addSql('CREATE TABLE institute_question_title (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, active BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE institute_answer ADD CONSTRAINT FK_2B2962FC697B0F4C FOREIGN KEY (institute_id) REFERENCES institute (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE institute_answer ADD CONSTRAINT FK_2B2962FC10F3A34 FOREIGN KEY (subtitle_id) REFERENCES institute_question_subtitle (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE institute_question_subtitle ADD CONSTRAINT FK_E2CE34E5A9F87BD FOREIGN KEY (title_id) REFERENCES institute_question_title (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE institute_answer DROP CONSTRAINT FK_2B2962FC697B0F4C');
        $this->addSql('ALTER TABLE institute_answer DROP CONSTRAINT FK_2B2962FC10F3A34');
        $this->addSql('ALTER TABLE institute_question_subtitle DROP CONSTRAINT FK_E2CE34E5A9F87BD');
        $this->addSql('DROP TABLE institute_answer');
        $this->addSql('DROP TABLE institute_question_subtitle');
        $this->addSql('DROP TABLE institute_question_title');
    }
}
