<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250105143122 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE institution_answer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, link TEXT DEFAULT NULL, status BOOLEAN NOT NULL, institution_id INT NOT NULL, question_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4F83183C10405986 ON institution_answer (institution_id)');
        $this->addSql('CREATE INDEX IDX_4F83183C1E27F6BF ON institution_answer (question_id)');
        $this->addSql('ALTER TABLE institution_answer ADD CONSTRAINT FK_4F83183C10405986 FOREIGN KEY (institution_id) REFERENCES institutions (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE institution_answer ADD CONSTRAINT FK_4F83183C1E27F6BF FOREIGN KEY (question_id) REFERENCES institution_question_option (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE institution_answer DROP CONSTRAINT FK_4F83183C10405986');
        $this->addSql('ALTER TABLE institution_answer DROP CONSTRAINT FK_4F83183C1E27F6BF');
        $this->addSql('DROP TABLE institution_answer');
    }
}
