<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240322065624 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE offence_list (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, points INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE user_info ADD offence_list_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE user_info ADD CONSTRAINT FK_B1087D9EA9DFB1A4 FOREIGN KEY (offence_list_id) REFERENCES offence_list (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_B1087D9EA9DFB1A4 ON user_info (offence_list_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('DROP TABLE offence_list');
        $this->addSql('ALTER TABLE user_info DROP CONSTRAINT FK_B1087D9EA9DFB1A4');
        $this->addSql('DROP INDEX IDX_B1087D9EA9DFB1A4');
        $this->addSql('ALTER TABLE user_info DROP offence_list_id');
    }
}
