<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240228045734 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE awards_and_link (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, link TEXT NOT NULL, user_progress_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_113E0979EAC04E5C ON awards_and_link (user_progress_id)');
        $this->addSql('CREATE TABLE user_info (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, user_id INT NOT NULL, institut VARCHAR(255) NOT NULL, position VARCHAR(255) NOT NULL, regular VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE user_progress (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, degree VARCHAR(255) DEFAULT NULL, rank VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE awards_and_link ADD CONSTRAINT FK_113E0979EAC04E5C FOREIGN KEY (user_progress_id) REFERENCES user_progress (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE awards_and_link DROP CONSTRAINT FK_113E0979EAC04E5C');
        $this->addSql('DROP TABLE awards_and_link');
        $this->addSql('DROP TABLE user_info');
        $this->addSql('DROP TABLE user_progress');
    }
}
