<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20241118132951 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE inst_qout_link_subtitle (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, points INT NOT NULL, award_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F08905123D5282CF ON inst_qout_link_subtitle (award_id)');
        $this->addSql('CREATE TABLE inst_qout_link_title (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE inst_qout_link_subtitle ADD CONSTRAINT FK_F08905123D5282CF FOREIGN KEY (award_id) REFERENCES inst_qout_link_title (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE inst_qout_link_subtitle DROP CONSTRAINT FK_F08905123D5282CF');
        $this->addSql('DROP TABLE inst_qout_link_subtitle');
        $this->addSql('DROP TABLE inst_qout_link_title');
    }
}
