<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20241217165812 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
//        $this->addSql('ALTER TABLE user_inst_qout_link DROP CONSTRAINT fk_54cb6484697b0f4c');
//        $this->addSql('ALTER TABLE user_inst_qout_link DROP CONSTRAINT fk_54cb64843d5282cf');
        $this->addSql('ALTER TABLE user_inst_qwith_link_subtitle DROP CONSTRAINT fk_6ebc84da697b0f4c');
        $this->addSql('ALTER TABLE user_inst_qwith_link_subtitle DROP CONSTRAINT fk_6ebc84da3d5282cf');
        $this->addSql('ALTER TABLE user_inst_qout_link_subtitle DROP CONSTRAINT fk_4958ac43697b0f4c');
        $this->addSql('ALTER TABLE user_inst_qout_link_subtitle DROP CONSTRAINT fk_4958ac433d5282cf');
        $this->addSql('ALTER TABLE user_inst_qwith_link DROP CONSTRAINT fk_6ef7f8bc3d5282cf');
        $this->addSql('ALTER TABLE user_inst_qwith_link DROP CONSTRAINT fk_6ef7f8bc697b0f4c');
        $this->addSql('ALTER TABLE inst_qwith_link_subtitle DROP CONSTRAINT fk_726934113d5282cf');
        $this->addSql('ALTER TABLE inst_qout_link_subtitle DROP CONSTRAINT fk_f08905123d5282cf');
        $this->addSql('DROP TABLE user_inst_qout_link');
        $this->addSql('DROP TABLE user_inst_qwith_link_subtitle');
        $this->addSql('DROP TABLE user_inst_qout_link_subtitle');
        $this->addSql('DROP TABLE inst_qout_link_title');
        $this->addSql('DROP TABLE user_inst_qwith_link');
        $this->addSql('DROP TABLE inst_qwith_link_title');
        $this->addSql('DROP TABLE inst_qwith_link_subtitle');
        $this->addSql('DROP TABLE inst_qout_link_subtitle');
        $this->addSql('DROP TABLE inst_qout_link');
        $this->addSql('DROP TABLE inst_qwith_link');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('CREATE TABLE user_inst_qout_link (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, institute_id INT NOT NULL, award_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_54cb64843d5282cf ON user_inst_qout_link (award_id)');
        $this->addSql('CREATE INDEX idx_54cb6484697b0f4c ON user_inst_qout_link (institute_id)');
        $this->addSql('CREATE TABLE user_inst_qwith_link_subtitle (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(255) NOT NULL, link TEXT NOT NULL, institute_id INT DEFAULT NULL, award_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_6ebc84da3d5282cf ON user_inst_qwith_link_subtitle (award_id)');
        $this->addSql('CREATE INDEX idx_6ebc84da697b0f4c ON user_inst_qwith_link_subtitle (institute_id)');
        $this->addSql('CREATE TABLE user_inst_qout_link_subtitle (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(255) NOT NULL, institute_id INT NOT NULL, award_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_4958ac433d5282cf ON user_inst_qout_link_subtitle (award_id)');
        $this->addSql('CREATE INDEX idx_4958ac43697b0f4c ON user_inst_qout_link_subtitle (institute_id)');
        $this->addSql('CREATE TABLE inst_qout_link_title (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE user_inst_qwith_link (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, link TEXT NOT NULL, status VARCHAR(255) NOT NULL, institute_id INT NOT NULL, award_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_6ef7f8bc697b0f4c ON user_inst_qwith_link (institute_id)');
        $this->addSql('CREATE INDEX idx_6ef7f8bc3d5282cf ON user_inst_qwith_link (award_id)');
        $this->addSql('CREATE TABLE inst_qwith_link_title (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE inst_qwith_link_subtitle (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, points INT NOT NULL, award_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_726934113d5282cf ON inst_qwith_link_subtitle (award_id)');
        $this->addSql('CREATE TABLE inst_qout_link_subtitle (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, points INT NOT NULL, award_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_f08905123d5282cf ON inst_qout_link_subtitle (award_id)');
        $this->addSql('CREATE TABLE inst_qout_link (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, points INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE inst_qwith_link (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, points INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE user_inst_qout_link ADD CONSTRAINT fk_54cb6484697b0f4c FOREIGN KEY (institute_id) REFERENCES institutions (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_inst_qout_link ADD CONSTRAINT fk_54cb64843d5282cf FOREIGN KEY (award_id) REFERENCES inst_qout_link (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_inst_qwith_link_subtitle ADD CONSTRAINT fk_6ebc84da697b0f4c FOREIGN KEY (institute_id) REFERENCES institutions (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_inst_qwith_link_subtitle ADD CONSTRAINT fk_6ebc84da3d5282cf FOREIGN KEY (award_id) REFERENCES inst_qwith_link_subtitle (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_inst_qout_link_subtitle ADD CONSTRAINT fk_4958ac43697b0f4c FOREIGN KEY (institute_id) REFERENCES institutions (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_inst_qout_link_subtitle ADD CONSTRAINT fk_4958ac433d5282cf FOREIGN KEY (award_id) REFERENCES inst_qout_link_subtitle (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_inst_qwith_link ADD CONSTRAINT fk_6ef7f8bc3d5282cf FOREIGN KEY (award_id) REFERENCES inst_qwith_link (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_inst_qwith_link ADD CONSTRAINT fk_6ef7f8bc697b0f4c FOREIGN KEY (institute_id) REFERENCES institutions (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE inst_qwith_link_subtitle ADD CONSTRAINT fk_726934113d5282cf FOREIGN KEY (award_id) REFERENCES inst_qwith_link_title (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE inst_qout_link_subtitle ADD CONSTRAINT fk_f08905123d5282cf FOREIGN KEY (award_id) REFERENCES inst_qout_link_title (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
}
