<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240317135031 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE innovative_education_list (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE innovative_education_subtitle (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) DEFAULT NULL, points INT NOT NULL, title_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_610308AEA9F87BD ON innovative_education_subtitle (title_id)');
        $this->addSql('CREATE TABLE user_innovative_education (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, link TEXT NOT NULL, user_id INT DEFAULT NULL, innovative_education_subtitle_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4043467AA76ED395 ON user_innovative_education (user_id)');
        $this->addSql('CREATE INDEX IDX_4043467AE4776E89 ON user_innovative_education (innovative_education_subtitle_id)');
        $this->addSql('ALTER TABLE innovative_education_subtitle ADD CONSTRAINT FK_610308AEA9F87BD FOREIGN KEY (title_id) REFERENCES innovative_education_list (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_innovative_education ADD CONSTRAINT FK_4043467AA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_innovative_education ADD CONSTRAINT FK_4043467AE4776E89 FOREIGN KEY (innovative_education_subtitle_id) REFERENCES innovative_education_subtitle (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE innovative_education_subtitle DROP CONSTRAINT FK_610308AEA9F87BD');
        $this->addSql('ALTER TABLE user_innovative_education DROP CONSTRAINT FK_4043467AA76ED395');
        $this->addSql('ALTER TABLE user_innovative_education DROP CONSTRAINT FK_4043467AE4776E89');
        $this->addSql('DROP TABLE innovative_education_list');
        $this->addSql('DROP TABLE innovative_education_subtitle');
        $this->addSql('DROP TABLE user_innovative_education');
    }
}
