<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20241230121614 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE director (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, users_id INT NOT NULL, institute_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1E90D3F067B3B43D ON director (users_id)');
        $this->addSql('CREATE INDEX IDX_1E90D3F0697B0F4C ON director (institute_id)');
        $this->addSql('ALTER TABLE director ADD CONSTRAINT FK_1E90D3F067B3B43D FOREIGN KEY (users_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE director ADD CONSTRAINT FK_1E90D3F0697B0F4C FOREIGN KEY (institute_id) REFERENCES institutions (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE director DROP CONSTRAINT FK_1E90D3F067B3B43D');
        $this->addSql('ALTER TABLE director DROP CONSTRAINT FK_1E90D3F0697B0F4C');
        $this->addSql('DROP TABLE director');
    }
}
