controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute


api_login_check:
  path: /api/login


user_controllers:
  resource: ../src/Controller/user
  type: attribute
  prefix: /api/user

teacher_controllers:
  resource: ../src/Controller/Teacher
  type: attribute
  prefix: /api/teacher

director_controllers:
  resource: ../src/Controller/Director
  type: attribute
  prefix: /api/director

admin_controllers:
  resource: ../src/Controller/Admin
  type: attribute
  prefix: /api/admin

award_controllers:
  resource: ../src/Controller/Award
  type: attribute
  prefix: /api/award

rating_controllers:
  resource: ../src/Controller/rating
  type: attribute
  prefix: /api/rating

years_controllers:
  resource: ../src/Controller/Years
  type: attribute
  prefix: /years

expert_controllers:
  resource: ../src/Controller/Expert
  type: attribute
  prefix: /api/expert


auth_controllers:
  resource: ../src/Controller/Auth
  type: attribute